/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'lonelypiscis' at '09.02.17 10:46' with Gradle 3.0
 *
 * @author lonelypiscis, @date 09.02.17 10:46
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
